// Original Academy practice content for the 2026 general Bangla-medium scope.
// Textbook titles and unit maps are study references; answers and tests here are original practice, not official papers.
const ACADEMY_SSC_UNITS = [
  { title: 'Sense of Self', focus: 'Identity, self-awareness, and how people understand themselves.' },
  { title: 'Climate Change', focus: 'Climate risks, Bangladesh, and practical responses.' },
  { title: 'Pastimes', focus: 'Leisure, reading, hobbies, and changing ways to spend free time.' },
  { title: 'Events and Festivals', focus: 'Mother’s Day, May Day, Language Day, Independence Day, and Pahela Baishakh.' },
  { title: 'Problems Around Us', focus: 'Everyday social and environmental problems and possible solutions.' },
  { title: 'Our Neighbours', focus: 'South Asian neighbours, places, people, and shared regional life.' },
  { title: 'People Who Stand Out', focus: 'Artists, innovators, and people whose work benefits others.' },
  { title: 'World Heritage', focus: 'Cultural and natural heritage sites in Bangladesh and the world.' },
  { title: 'Unconventional Jobs', focus: 'Different occupations, skills, and changing career choices.' },
  { title: 'Dreams', focus: 'Personal hopes, goals, and stories of people who pursued them.' },
  { title: 'Reading from English Literature', focus: 'Literary texts, poems, stories, interpretation, and response.' },
  { title: 'Roots', focus: 'Family, place, heritage, and a sense of belonging.' },
  { title: 'Loneliness', focus: 'Relationships, feelings, and human connection.' },
  { title: 'Renewable Energy', focus: 'Clean energy sources and their role in a sustainable future.' },
  { title: 'Media and Modes of E-communication', focus: 'Digital communication, social networks, and e-learning.' },
  { title: 'Graffiti', focus: 'Public expression, art, messages, and community space.' }
];
const ACADEMY_SSC_TESTS = [
  {
    id: 'ssc-writing-paper1', title: 'English 1st Paper · Writing Test', badge: 'SSC 2026 structure · Part B · 30 marks',
    note: 'The SSC 2026 writing section has two tasks: completing a story (15) and writing a dialogue (15). This original practice set is not an official question paper.',
    tasks: [
      { label: 'Question 10 · Complete the story · 15 marks', prompt: 'A storm caused a power cut in a village. On the way home, Rafi saw a small light moving near the canal. Continue the story and give it a suitable title.', writingId: 'c910-story-storm' },
      { label: 'Question 11 · Write a dialogue · 15 marks', prompt: 'Write a dialogue between two friends about using mobile phones wisely.', writingId: 'c910-dialogue-mobile' }
    ]
  },
  {
    id: 'ssc-writing-paper2', title: 'English 2nd Paper · Writing Test', badge: 'SSC 2026 structure · Part B · 40 marks',
    note: 'The SSC 2026 writing section has a paragraph (10), an email/letter/application (10), and a short composition (20). This original practice set is not an official question paper.',
    tasks: [
      { label: 'Question 10 · Paragraph · 10 marks', prompt: 'Write a paragraph on “Tree Plantation” in about 150–180 words.', writingId: 'c910-paragraph-trees' },
      { label: 'Question 11 · Application · 10 marks', prompt: 'Write to your Head Teacher requesting a debating club for your school.', writingId: 'c910-application-debate-g9' },
      { label: 'Question 12 · Short composition · 20 marks', prompt: 'Write a short composition on “The Wonders of Modern Science”.', writingId: 'c910-composition-science' }
    ]
  },
  {
    id: 'ssc-language-clinic', title: 'English 2nd Paper · Grammar check', badge: 'Practice drill · 9 common item types',
    note: 'A short self-check across the grammar item types listed in the SSC 2026 English 2nd Paper structure. This is a practice drill, not a complete 60-mark grammar paper.',
    sections: [
      { label: 'Gap filling', items: [{ prompt: 'A good student is attentive ___ class.', answer: 'in' }] },
      { label: 'Substitution table', items: [{ prompt: 'Make a sentence: Trees / give / us shade.', answer: 'Trees give us shade.' }] },
      { label: 'Right form of verbs', items: [{ prompt: 'If we ___ (plant) trees, the air becomes cleaner.', answer: 'plant' }] },
      { label: 'Changing sentences', items: [{ prompt: 'Change to negative without changing the meaning: Everyone likes a peaceful place.', answer: 'There is nobody who does not like a peaceful place. (One acceptable form.)' }] },
      { label: 'Tag question', items: [{ prompt: 'Trees are useful, ___?', answer: 'aren’t they?' }] },
      { label: 'Prefix or suffix', items: [{ prompt: 'Trees are (use) ___ to people.', answer: 'useful' }] },
      { label: 'Preposition', items: [{ prompt: 'We should care ___ the environment.', answer: 'for' }] },
      { label: 'Connector', items: [{ prompt: 'Trees give us oxygen, ___ they help keep the air fresh.', answer: 'and' }] },
      { label: 'Punctuation', items: [{ prompt: 'Rewrite correctly: rahim said we should plant trees', answer: 'Rahim said, “We should plant trees.”' }] }
    ]
  }
];


const ACADEMY_SSC_TESTS_CLASS10 = ACADEMY_SSC_TESTS.map(test => {
  const answerIds = {
    'c910-story-storm': 'c910-story-fire',
    'c910-dialogue-mobile': 'c910-dialogue-exam',
    'c910-paragraph-trees': 'c910-paragraph-reading',
    'c910-application-debate-g9': 'c910-letter-study-tour',
    'c910-composition-science': 'c910-composition-renewable'
  };
  const prompts = {
    'c910-story-storm': 'A student saw smoke coming from a small shop near the school. Complete the story, showing how people respond safely.',
    'c910-dialogue-mobile': 'Write a dialogue between two classmates about preparing sensibly for the SSC examination.',
    'c910-paragraph-trees': 'Write a paragraph about the importance of reading for students.',
    'c910-application-debate-g9': 'Write a letter to a friend describing an educational study tour.',
    'c910-composition-science': 'Write a short composition on the importance of renewable energy.'
  };
  return {
    ...test,
    id: `${test.id}-class10`,
    tasks: test.tasks ? test.tasks.map(task => ({ ...task, writingId: answerIds[task.writingId] || task.writingId, prompt: prompts[task.writingId] || task.prompt, label: task.writingId === 'c910-application-debate-g9' ? 'Question 11 · Letter · 10 marks' : task.label })) : undefined
  };
});

export const ACADEMY_CONTENT = {
  year: 2026,
  track: 'General curriculum · Bangla-medium',
  sourceNote: 'Book lists are checked against NCTB’s 2026 catalogue. Class 6–8 practice follows textbook themes and skills; no single national paper format is claimed for those classes. Class 9–10 practice uses the published SSC 2026 English writing structure. All Academy tests and model answers are original practice.',
  sources: {
    6: 'https://nctb.gov.bd/pages/static-pages/695b987ac4774958d7b7040b',
    7: 'https://nctb.gov.bd/pages/static-pages/695b9aeec4774958d7b70908',
    8: 'https://nctb.gov.bd/pages/static-pages/695b9858c4774958d7b703d8',
    9: 'https://nctb.gov.bd/pages/static-pages/695b99afc4774958d7b70612',
    10: 'https://nctb.gov.bd/pages/static-pages/695b99afc4774958d7b70612',
    ssc2026: 'https://nctb.gov.bd/pages/notices/6922e919dbfbab28ce0abfac'
  },
  grades: {
    6: {
      books: ['English for Today', 'English Grammar and Composition'],
      units: [
        { title: 'Lessons 1–5 · Starting school and daily communication', focus: 'Going to a new school; congratulations; a railway station; where people are from; thanking someone for their work.' },
        { title: 'Lessons 6–10 · Senses, help, shopping, and health', focus: 'Food and smell; helping hands; grocery shopping; health; modern and traditional remedies.' },
        { title: 'Lessons 11–16 · Listening, Bangladesh, and stories', focus: 'Listening practice; the beauty of Bangladesh; national pride; a lion; an old people’s home; boats on rivers.' },
        { title: 'Lessons 17–22 · Food, safety, music, and the wider world', focus: 'Listening; making snacks; road safety; Hason Raja; wonders of the world; global connections.' },
        { title: 'Lessons 23–28 · Work, culture, clothes, and people', focus: 'The global village; wage earners; the Concert for Bangladesh; buying clothes; a story about Andre; listening.' },
        { title: 'Lessons 29–33 · Tests, water, invitations, and nature', focus: 'Taking a test; what we should do; too much or too little water; an invitation; the garden.' }
      ],
      grammar: ['Simple sentence building and questions', 'Common nouns, pronouns, verbs, and adjectives', 'Everyday vocabulary and spelling', 'Capital letters and basic punctuation', 'Guided paragraphs, short dialogues, and story completion'],
      writingFormats: ['Short paragraph', 'Short dialogue', 'Guided story completion', 'Simple email or letter', 'Short composition'],
      tests: [
        {
          id: 'c6-test-school', title: 'New school · reading and language', badge: 'Textbook-mapped practice · not an official paper',
          passageTitle: 'A helpful first day', passage: 'On her first day at a new school, Nila arrived early with her older sister. A girl named Rupa showed her the classroom and introduced her to the teacher. At break time, they shared fruit and talked about their favourite subjects. Nila felt less nervous and decided to join the school garden club.',
          sections: [
            { label: 'Read and answer', items: [
              { prompt: 'Who came to school with Nila?', answer: 'Her older sister.' },
              { prompt: 'How did Rupa help Nila?', answer: 'She showed Nila the classroom and introduced her to the teacher.' },
              { prompt: 'What club did Nila decide to join?', answer: 'The school garden club.' }
            ] },
            { label: 'Language focus', items: [
              { prompt: 'Complete: Nila ___ early. (arrive)', answer: 'arrived' },
              { prompt: 'Choose the opposite of “nervous”: calm / noisy / hungry.', answer: 'calm' },
              { prompt: 'Add punctuation: rupa said welcome to our class', answer: 'Rupa said, “Welcome to our class.”' }
            ] }
          ],
          writingPrompt: 'Write a short paragraph about your first day at school.', writingId: 'c6-paragraph-new-school'
        },
        {
          id: 'c6-test-health', title: 'Healthy habits · reading and writing', badge: 'Textbook-mapped practice · self-paced',
          passageTitle: 'A simple healthy routine', passage: 'Mahir drinks a glass of clean water after waking up. He eats rice, vegetables, and an egg for breakfast. He walks to school with his friend and washes his hands before lunch. In the evening, he plays outside and goes to bed on time. His family says that small habits help him stay active.',
          sections: [
            { label: 'Read and answer', items: [
              { prompt: 'What does Mahir drink after waking up?', answer: 'A glass of clean water.' },
              { prompt: 'When does he wash his hands?', answer: 'Before lunch.' },
              { prompt: 'Name one habit that helps Mahir stay active.', answer: 'He walks to school, plays outside, eats a balanced breakfast, or goes to bed on time.' }
            ] },
            { label: 'Language focus', items: [
              { prompt: 'Choose: Mahir (wash / washes) his hands before lunch.', answer: 'washes' },
              { prompt: 'Put in order: hands / before lunch / washes / he / his.', answer: 'He washes his hands before lunch.' },
              { prompt: 'Write the plural of “habit”.', answer: 'habits' }
            ] }
          ],
          writingPrompt: 'Write a short dialogue between two friends about healthy habits.', writingId: 'c6-dialogue-healthy-habits'
        }
      ]
    },
    7: {
      books: ['English for Today', 'English Grammar and Composition'],
      units: [
        { title: 'Unit 1 · Attention, please', focus: 'Classroom language, directions, requests, and announcements.' },
        { title: 'Unit 2 · My Study Guide', focus: 'Study habits, reference skills, and using a dictionary.' },
        { title: 'Unit 3 · What are friends for?', focus: 'Friendship, school life, and understanding other people.' },
        { title: 'Unit 4 · People Who Make a Difference', focus: 'Teachers, helpful people, and everyday acts that matter.' },
        { title: 'Unit 5 · Great Women to Remember', focus: 'The lives and contributions of Begum Rokeya and Helen Keller.' },
        { title: 'Unit 6 · Leisure', focus: 'Free-time activities, reading, poems, travel, and stories.' },
        { title: 'Unit 7 · Games and Sports', focus: 'Sports, players, teamwork, and healthy competition.' },
        { title: 'Unit 8 · Likes and Dislikes', focus: 'Talking about preferences and familiar interests.' },
        { title: 'Unit 9 · Climate Change', focus: 'Climate effects in Bangladesh and ways to care for the environment.' }
      ],
      grammar: ['Tenses and subject–verb agreement', 'Articles, pronouns, and prepositions', 'Questions, connectors, and punctuation', 'Vocabulary in context and dictionary skills', 'Paragraphs, dialogues, informal letters, and story completion'],
      writingFormats: ['Paragraph', 'Dialogue', 'Informal letter or email', 'Story completion', 'Short composition'],
      tests: [
        {
          id: 'c7-test-climate', title: 'Climate change · reading and language', badge: 'Textbook-mapped practice · not an official paper',
          passageTitle: 'A greener school', passage: 'After a very hot week, Class Seven discussed how to make their school grounds cooler. The students planted native trees near the playground and placed water bowls for birds. Their teacher asked them to save water and keep plastic out of the drain. The class agreed to care for the plants in turns and explain their work at assembly.',
          sections: [
            { label: 'Read and answer', items: [
              { prompt: 'Why did the students want to make the school grounds cooler?', answer: 'They had experienced a very hot week.' },
              { prompt: 'Name two actions the class took or planned.', answer: 'They planted native trees, put out water for birds, saved water, avoided plastic in drains, or took turns caring for plants.' },
              { prompt: 'What would the class explain at assembly?', answer: 'They would explain their environmental work.' }
            ] },
            { label: 'Language focus', items: [
              { prompt: 'Complete: The students ___ native trees last week. (plant)', answer: 'planted' },
              { prompt: 'Join with “because”: They saved water. Water is precious.', answer: 'They saved water because it is precious.' },
              { prompt: 'Choose the best connector: Trees give shade, (but / so) the yard feels cooler.', answer: 'so' }
            ] }
          ],
          writingPrompt: 'Write a paragraph about climate change in Bangladesh and one action students can take.', writingId: 'c7-paragraph-climate'
        },
        {
          id: 'c7-test-sport', title: 'Games and sports · reading and writing', badge: 'Textbook-mapped practice · self-paced',
          passageTitle: 'The class football team', passage: 'The Class Seven football team practised twice a week after lessons. Their captain, Tuhin, reminded everyone to warm up and pass the ball fairly. The team lost its first match, but the players congratulated the other school and discussed what they could improve. At the next match, they worked together and played with confidence.',
          sections: [
            { label: 'Read and answer', items: [
              { prompt: 'How often did the team practise?', answer: 'Twice a week.' },
              { prompt: 'What did Tuhin remind the players to do?', answer: 'Warm up and pass the ball fairly.' },
              { prompt: 'What did the players do after losing?', answer: 'They congratulated the other school and discussed how to improve.' }
            ] },
            { label: 'Language focus', items: [
              { prompt: 'Write the past tense of “play”.', answer: 'played' },
              { prompt: 'Choose the adjective: confidence / confident / confidently.', answer: 'confident' },
              { prompt: 'Add a question tag: The team practised twice a week, ___?', answer: 'didn’t it?' }
            ] }
          ],
          writingPrompt: 'Write a dialogue between two friends about the value of games and sports.', writingId: 'c7-dialogue-sports'
        }
      ]
    },
    8: {
      books: ['English for Today', 'English Grammar and Composition'],
      units: [
        { title: 'Unit 1 · A Glimpse of Our Culture', focus: 'Folk songs, nakshi kantha, ethnic communities, cuisine, and children’s songs.' },
        { title: 'Unit 2 · Food and Nutrition', focus: 'Good food, food groups, daily diets, and a delicious dish.' },
        { title: 'Unit 3 · Health and Hygiene', focus: 'Personal health, hygiene, physical exercise, family well-being, and teamwork.' },
        { title: 'Unit 4 · Check Your References', focus: 'Contents pages, dictionaries, meanings, synonyms, and antonyms.' },
        { title: 'Unit 5 · Humans and Environment', focus: 'Nature, animals, environmental care, and local cultures.' },
        { title: 'Unit 6 · Going on a Trip', focus: 'Air travel, forms, announcements, destinations, and a floating market.' },
        { title: 'Unit 7 · Occupations at Risk', focus: 'Pearl divers, river gypsies, and people whose livelihoods face change.' },
        { title: 'Unit 8 · News! News! News!', focus: 'News, newspapers, television reports, and interviews.' },
        { title: 'Unit 9 · Things That Have Changed Our Lives', focus: 'The wheel, transport, inventions, and how technology changes life.' },
        { title: 'Unit 10 · Fables', focus: 'The truthful dove and other stories, including lessons about choices.' },
        { title: 'Unit 11 · Women’s Role in Uprisings', focus: 'Women’s courage, participation, and sacrifice in struggles for freedom.' }
      ],
      grammar: ['Reference and dictionary skills; meaning, synonyms, and antonyms', 'Verb forms, tense consistency, and sentence structure', 'Connectors, prepositions, and punctuation', 'Paragraphs, dialogues, letters/emails, and guided story completion'],
      writingFormats: ['Paragraph', 'Dialogue', 'Email or letter', 'Story completion', 'Short composition'],
      tests: [
        {
          id: 'c8-test-food', title: 'Food and nutrition · reading and language', badge: 'Textbook-mapped practice · not an official paper',
          passageTitle: 'Lunch for the excursion', passage: 'Before the class excursion, the students planned a simple lunch. They packed rice, lentils, vegetables, fruit, and clean drinking water. Their teacher explained that a balanced meal gives the body energy and helps students concentrate. The class used reusable bottles and collected every wrapper before leaving the picnic area.',
          sections: [
            { label: 'Read and answer', items: [
              { prompt: 'What foods did the students pack?', answer: 'Rice, lentils, vegetables, fruit, and clean drinking water.' },
              { prompt: 'How can a balanced meal help students?', answer: 'It gives them energy and helps them concentrate.' },
              { prompt: 'How did the class reduce waste?', answer: 'They used reusable bottles and collected every wrapper.' }
            ] },
            { label: 'Language focus', items: [
              { prompt: 'Complete: A balanced meal ___ (give) the body energy.', answer: 'gives' },
              { prompt: 'Find a word in the passage meaning “pay attention”.', answer: 'concentrate' },
              { prompt: 'Join with “and”: They used reusable bottles. They collected every wrapper.', answer: 'They used reusable bottles and collected every wrapper.' }
            ] }
          ],
          writingPrompt: 'Write a paragraph about healthy food habits for students.', writingId: 'c8-paragraph-food'
        },
        {
          id: 'c8-test-trip', title: 'Going on a trip · reading and writing', badge: 'Textbook-mapped practice · self-paced',
          passageTitle: 'A journey by air', passage: 'Sadia checked her ticket before entering the airport. At the counter, she showed her passport and placed her bag on the scale. After the security check, she listened to the announcement and walked to the gate with her family. During the flight, she looked out of the window and wrote a few notes about the clouds and the river below.',
          sections: [
            { label: 'Read and answer', items: [
              { prompt: 'What did Sadia check before entering the airport?', answer: 'Her ticket.' },
              { prompt: 'What did she do after security?', answer: 'She listened to the announcement and walked to the gate.' },
              { prompt: 'What did she write notes about?', answer: 'The clouds and the river below.' }
            ] },
            { label: 'Language focus', items: [
              { prompt: 'Write the past tense of “write”.', answer: 'wrote' },
              { prompt: 'Choose the correct preposition: She looked (at / in) the window.', answer: 'at' },
              { prompt: 'Put in order: the gate / walked / she / to.', answer: 'She walked to the gate.' }
            ] }
          ],
          writingPrompt: 'Write a dialogue between two friends planning a class trip.', writingId: 'c8-dialogue-trip'
        }
      ]
    },
    9: {
      books: ['English for Today', 'English Grammar and Composition'], units: ACADEMY_SSC_UNITS,
      grammar: ['Gap filling with clues', 'Substitution tables and right forms of verbs', 'Sentence transformation and tag questions', 'Prefixes/suffixes, prepositions, and connectors', 'Punctuation and capitalization'],
      writingFormats: ['English 1st Paper: completing a story and writing a dialogue', 'English 2nd Paper: paragraph, email/letter/application, and short composition'],
      tests: ACADEMY_SSC_TESTS
    },
    10: {
      books: ['English for Today', 'English Grammar and Composition'], units: ACADEMY_SSC_UNITS,
      grammar: ['Gap filling with clues', 'Substitution tables and right forms of verbs', 'Sentence transformation and tag questions', 'Prefixes/suffixes, prepositions, and connectors', 'Punctuation and capitalization'],
      writingFormats: ['English 1st Paper: completing a story and writing a dialogue', 'English 2nd Paper: paragraph, email/letter/application, and short composition'],
      tests: ACADEMY_SSC_TESTS_CLASS10
    }
  },
  writing: [
    { id: 'c6-paragraph-new-school', grade: 6, type: 'paragraph', title: 'My First Day at a New School', unit: 'English for Today · Going to a New School', prompt: 'Write a short paragraph about your first day at a new school.', modelAnswer: 'My first day at a new school was exciting. I went there with my mother and reached before the bell rang. The school building looked large, and I felt a little shy. A friendly classmate showed me my classroom. My teacher welcomed me and helped me find my seat. At break time, I talked with two students and shared my tiffin. I liked the clean playground and the school garden. Soon I felt comfortable. I hope to learn many new things and make good friends at my new school.', banglaNote: 'সহজভাবে শুরু করো—কখন গিয়েছিলে, কেমন লেগেছিল, কে সাহায্য করেছিল, শেষে কী আশা করো।' },
    { id: 'c6-paragraph-school', grade: 6, type: 'paragraph', title: 'My School', unit: 'School life', prompt: 'Write a short paragraph about your school.', modelAnswer: 'The name of my school is Mymensingh Model School. It is near my home. The school has many classrooms, a library, a playground, and a garden. Our teachers are kind and helpful. They teach us English, Bangla, mathematics, science, and other subjects. I enjoy reading in the library and playing with my friends after class. We keep our classrooms clean and respect one another. My school helps me learn good habits as well as lessons. I love my school very much.', banglaNote: 'নাম ও অবস্থান দিয়ে শুরু করো; ভবন, শিক্ষক, পড়াশোনা, ভালো লাগার কারণ—এই ধারায় লিখো।' },
    { id: 'c6-paragraph-friend', grade: 6, type: 'paragraph', title: 'My Best Friend', unit: 'Friendship and school life', prompt: 'Write a short paragraph about your best friend.', modelAnswer: 'My best friend is Rafi. He is in my class and lives near my house. He is cheerful, honest, and helpful. We study together after school and play badminton in the afternoon. Rafi shares his books when I forget mine. He also listens carefully when a friend has a problem. We do not always like the same games, but we respect each other’s choices. I feel happy when we work as a team. I hope we will remain good friends for many years.', banglaNote: 'বন্ধুর পরিচয়, স্বভাব, একসঙ্গে কী করো, এবং কেন বন্ধুত্বটি মূল্যবান—এসব বলো।' },
    { id: 'c6-paragraph-routine', grade: 6, type: 'paragraph', title: 'My Daily Routine', unit: 'Daily life', prompt: 'Write a short paragraph about your daily routine.', modelAnswer: 'I get up at six o’clock in the morning. I wash, get dressed, and eat breakfast with my family. Then I go to school and attend my lessons carefully. I return home in the afternoon and take some rest. After that, I finish my homework and help my younger sister with her reading. I play outside for a short time before dinner. At night, I pack my schoolbag and read a storybook. I go to bed by ten o’clock so that I can wake up fresh the next day.', banglaNote: 'দিনের কাজগুলো সময়ের ক্রমে লেখো; simple present tense ব্যবহার করো।' },
    { id: 'c6-paragraph-rainy', grade: 6, type: 'paragraph', title: 'A Rainy Day', unit: 'Weather and everyday life', prompt: 'Write a short paragraph about a rainy day.', modelAnswer: 'A rainy day is different from a sunny day. Dark clouds cover the sky, and rain falls on the roads, trees, and roofs. People use umbrellas or raincoats when they go outside. Sometimes water gathers on the streets, so walking becomes difficult. I enjoy watching the raindrops from our window. My mother makes hot khichuri, and our family eats together. Birds sit under the trees to stay dry. After the rain stops, the air feels cool and fresh. A rainy day can be troublesome, but it is beautiful too.', banglaNote: 'আকাশ, মানুষের কাজ, নিজের অভিজ্ঞতা ও অনুভূতি—চারটি দিক রাখো।' },
    { id: 'c6-dialogue-new-friend', grade: 6, type: 'dialogue', title: 'Meeting a New Classmate', unit: 'English for Today · introductions', prompt: 'Write a short dialogue between two students who meet on the first day of school.', modelAnswer: 'Rina: Hello. Is this Class Six?\nMina: Yes, it is. Are you new here?\nRina: Yes. My name is Rina. What is your name?\nMina: I am Mina. Nice to meet you.\nRina: Nice to meet you too. Where should I sit?\nMina: You can sit beside me. The teacher will come soon.\nRina: Thank you. Which subject do you like best?\nMina: I like English. What about you?\nRina: I like science. Perhaps we can study together.\nMina: That sounds good. Welcome to our class!', banglaNote: 'সম্ভাষণ, পরিচয়, একটি প্রশ্ন, বন্ধুত্বপূর্ণ উত্তর ও বিদায়—সংক্ষিপ্ত পালা রাখো।' },
    { id: 'c6-dialogue-station', grade: 6, type: 'dialogue', title: 'At the Railway Station', unit: 'English for Today · At a railway station', prompt: 'Write a short dialogue between a passenger and a station assistant asking for information.', modelAnswer: 'Passenger: Excuse me. When does the train for Dhaka leave?\nAssistant: It leaves at nine thirty.\nPassenger: Which platform should I use?\nAssistant: Please go to platform two.\nPassenger: Where can I buy a ticket?\nAssistant: The ticket counter is beside the main entrance.\nPassenger: Thank you. Is the train on time?\nAssistant: Yes, it is expected to arrive shortly.\nPassenger: Thank you for your help.\nAssistant: You are welcome. Have a safe journey.', banglaNote: 'ভদ্রভাবে প্রশ্ন করো; সময়, প্ল্যাটফর্ম ও টিকিটের মতো দরকারি তথ্য নাও।' },
    { id: 'c6-dialogue-healthy-habits', grade: 6, type: 'dialogue', title: 'Healthy Habits', unit: 'English for Today · Health is Wealth', prompt: 'Write a short dialogue between two friends about healthy habits.', modelAnswer: 'Nabil: You look energetic today. What do you do to stay healthy?\nSumi: I eat fruit and vegetables and drink clean water.\nNabil: Do you exercise every day?\nSumi: I walk and play outside after school. What about you?\nNabil: I ride my bicycle and go to bed on time.\nSumi: That is good. We should wash our hands before eating too.\nNabil: Yes, and we should keep our surroundings clean.\nSumi: Let us remind our classmates about these habits.\nNabil: Good idea. Small habits can keep us well.', banglaNote: 'খাবার, পানি, ব্যায়াম, ঘুম ও পরিচ্ছন্নতার দু-তিনটি উদাহরণ নাও।' },
    { id: 'c6-email-event', grade: 6, type: 'email', title: 'Email About a School Event', unit: 'School life · simple email', prompt: 'Write a short email to your cousin about a school event you enjoyed.', modelAnswer: 'To: Rima\nSubject: Our school cultural day\n\nDear Rima,\n\nHow are you? Yesterday our school held a cultural day. Students sang songs, recited poems, and performed a short play. I took part in a group song with my classmates. Our teachers and parents watched the programme. The hall was decorated with flowers and colourful paper. I enjoyed the day very much because everyone worked together. I wish you had been there.\n\nWrite to me soon.\n\nYour loving cousin,\nMitu', banglaNote: 'ইমেইলে To, Subject, greeting, মূল খবর, অনুভূতি ও closing রাখো।' },
    { id: 'c6-letter-bookfair', grade: 6, type: 'letter', title: 'A Letter About a Book Fair', unit: 'Reading and local events', prompt: 'Write a short letter to a friend describing a visit to a book fair.', modelAnswer: 'Dear Tania,\n\nI hope you are well. Last Friday I went to a book fair with my father. There were many stalls with storybooks, poems, science books, and picture books. I chose a book about animals and a small English dictionary. A group of children was reading stories in a quiet corner. We also saw a puppet show near the entrance. The fair was busy but enjoyable. I want to visit again with you next year.\n\nWith love,\nNusrat', banglaNote: 'চিঠিতে কোথায় ও কার সঙ্গে গিয়েছিলে, কী দেখেছিলে, কী কিনেছিলে—এসব বলো।' },
    { id: 'c6-story-crow', grade: 6, type: 'story', title: 'A Thirsty Crow', unit: 'Guided story completion', prompt: 'Complete the story “A Thirsty Crow” in your own words.', modelAnswer: 'One hot day, a crow felt very thirsty. It flew over fields and houses to find water. At last, it saw a pitcher under a tree. There was only a little water at the bottom, and the crow could not reach it with its beak. The crow looked around and found some small stones. It dropped the stones into the pitcher one by one. Slowly the water rose higher. The crow drank the water and flew away happily. The crow’s patience and clever idea helped it solve the problem.\n\nMoral: Where there is a will, there is a way.', banglaNote: 'সমস্যা, বুদ্ধি করে চেষ্টা, সমাধান—এই তিন ধাপে গল্প শেষ করো; নিজের ভাষায় লেখো।' },
    { id: 'c6-story-honest-woodcutter', grade: 6, type: 'story', title: 'The Honest Woodcutter', unit: 'Guided story completion', prompt: 'Complete a short story about a woodcutter who tells the truth after losing his axe.', modelAnswer: 'A poor woodcutter was cutting wood beside a river. One day his axe slipped from his hand and fell into the water. He sat down sadly because he could not afford another one. A kind spirit appeared and brought a golden axe. The woodcutter said it was not his. The spirit then showed him a silver axe, but he again told the truth. At last, the spirit brought his old iron axe. The woodcutter thanked the spirit and took it. Pleased with his honesty, the spirit gave him the other two axes as a reward.\n\nMoral: Honesty is the best policy.', banglaNote: 'woodcutter-এর সততা যেন কাজের মাধ্যমে বোঝা যায়; শেষে ছোট moral যোগ করো।' },
    { id: 'c6-composition-zoo', grade: 6, type: 'composition', title: 'A Visit to a Zoo', unit: 'Short composition · places and animals', prompt: 'Write a short composition about a visit to a zoo.', modelAnswer: 'Last winter, my family visited the National Zoo in Dhaka. We reached in the morning and bought our tickets at the gate. The zoo had many animals and birds. We saw deer, monkeys, colourful parrots, and a large elephant. I watched the giraffes eating leaves and learned how different animals live. My parents reminded me not to feed them or tap on the cages. We rested under a tree and ate our lunch. Before leaving, I read the signs about protecting wildlife. The visit was enjoyable and educational. I hope all animals in the zoo receive good care.', banglaNote: 'ভ্রমণের সময়, দেখা প্রাণী, শেখা বিষয় ও নিজের অনুভূতি—এই ক্রমে লেখো।' },

    { id: 'c7-paragraph-village-doctor', grade: 7, type: 'paragraph', title: 'A Village Doctor', unit: 'People who help others', prompt: 'Write a paragraph about a village doctor.', modelAnswer: 'A village doctor provides basic medical help to people who live far from a large hospital. He often works in a small chamber and visits patients at home when they are too ill to travel. He checks their symptoms, gives simple advice, and tells them when they need a qualified physician or hospital. Many villagers respect him because he is available nearby and understands local needs. A village doctor cannot replace a trained specialist, but he can guide people towards proper care. Clean clinics, safe medicine, and good training help him serve the community better.', banglaNote: 'ভূমিকা, কাজ, গ্রামের মানুষের উপকার, এবং সীমাবদ্ধতা—সব দিক ভারসাম্য রেখে লেখো।' },
    { id: 'c7-paragraph-sport', grade: 7, type: 'paragraph', title: 'My Favourite Sport', unit: 'Unit 7 · Games and Sports', prompt: 'Write a paragraph about your favourite sport.', modelAnswer: 'My favourite sport is football. I play it with my classmates on the school field whenever we have free time. Football keeps the body active and teaches us to work as a team. Each player has a role, so we have to pass the ball and pay attention to one another. I enjoy the excitement of a close match, but winning is not everything. We should follow the rules and respect the other team. I also watch important matches with my family. Football gives me exercise, friendship, and many happy memories.', banglaNote: 'কেন খেলাটি ভালো লাগে এবং কী শেখায়—দুটিই বলো; শেষে fair play-এর কথা রাখো।' },
    { id: 'c7-paragraph-climate', grade: 7, type: 'paragraph', title: 'Climate Change in Bangladesh', unit: 'Unit 9 · Climate Change', prompt: 'Write a paragraph about climate change in Bangladesh and one action students can take.', modelAnswer: 'Climate change is a long-term change in the usual weather patterns of the earth. Bangladesh is at risk because many people live near rivers and the coast. Rising sea levels, floods, cyclones, and unusual heat can damage homes, farms, and roads. Climate change affects people, animals, and crops. We can help by planting trees, saving electricity and water, and keeping drains free of plastic. Students can learn about the issue and share practical ideas with their families. These actions cannot solve the whole problem, but they help protect our surroundings and encourage responsible choices.', banglaNote: 'কারণ-প্রভাব-সমাধান এই তিন অংশে লেখো; বাংলাদেশের উদাহরণ দিয়ে বিষয়টি স্পষ্ট করো।' },
    { id: 'c7-paragraph-leisure', grade: 7, type: 'paragraph', title: 'How I Spend My Leisure Time', unit: 'Unit 6 · Leisure', prompt: 'Write a paragraph about how you spend your leisure time.', modelAnswer: 'Leisure time is the part of the day when we are free from schoolwork and other duties. I like to read storybooks, play badminton, and help my mother water the plants. Reading gives me new ideas, while outdoor games keep me healthy. Sometimes I listen to music with my family or draw pictures with my younger brother. I try not to spend all my free time looking at a screen. A good hobby makes leisure both pleasant and useful. I believe every student should have time to rest, play, and follow an interest.', banglaNote: 'অবসরের কাজগুলোর তালিকা নয়—কোন কাজ কীভাবে উপকার করে, সেটিও বোঝাও।' },
    { id: 'c7-paragraph-early-rising', grade: 7, type: 'paragraph', title: 'The Importance of Early Rising', unit: 'Daily life and healthy habits', prompt: 'Write a paragraph about the importance of early rising.', modelAnswer: 'Early rising means getting up early in the morning. The morning is often quiet and fresh, so it is a good time to prepare for the day. A student who wakes up on time can wash, eat breakfast, and reach school without rushing. Early rising also gives people time for a short walk or exercise. However, waking early is only helpful when we get enough sleep at night. We should go to bed at a sensible time and follow a regular routine. This habit can make the day calmer and more organised.', banglaNote: 'ভোরে ওঠার উপকার বলো, তবে পর্যাপ্ত ঘুমের কথাও উল্লেখ করো।' },
    { id: 'c7-dialogue-sports', grade: 7, type: 'dialogue', title: 'The Value of Games and Sports', unit: 'Unit 7 · Games and Sports', prompt: 'Write a dialogue between two friends about the value of games and sports.', modelAnswer: 'Rafi: You look tired after class. Shall we play football?\nSajib: I would like to, but I have homework to finish.\nRafi: We can play for half an hour and then study.\nSajib: That sounds fair. Games keep us fit, don’t they?\nRafi: Yes, and team games teach us cooperation.\nSajib: They also help us feel fresh after studying.\nRafi: We must follow the rules and respect the other team.\nSajib: I agree. Winning should not be more important than fair play.\nRafi: Let us ask two classmates to join us.\nSajib: Good idea. I will bring the ball.', banglaNote: 'দুই বন্ধুর পালা সমান রাখো; স্বাস্থ্য, সহযোগিতা ও নিয়ম মানার দিক আনো।' },
    { id: 'c7-dialogue-climate', grade: 7, type: 'dialogue', title: 'Taking Action on Climate Change', unit: 'Unit 9 · Climate Change', prompt: 'Write a dialogue between two classmates about actions they can take to care for the environment.', modelAnswer: 'Maya: Our teacher asked us to discuss climate change. What can students do?\nRony: We can plant trees and look after them instead of leaving them dry.\nMaya: We should also save electricity when we leave a classroom.\nRony: Yes. We can carry reusable bottles and avoid throwing plastic into drains.\nMaya: Does one class really make a difference?\nRony: It may seem small, but good habits spread when others see them.\nMaya: Let us make a short poster for the school assembly.\nRony: Good plan. We can include ways to save water too.', banglaNote: 'সমস্যা নিয়ে শুধু ভয় নয়—শিক্ষার্থীর পক্ষে সম্ভব এমন কাজের প্রস্তাব দাও।' },
    { id: 'c7-dialogue-pastime', grade: 7, type: 'dialogue', title: 'Choosing a Pastime', unit: 'Unit 6 · Leisure', prompt: 'Write a dialogue between two friends about their favourite pastimes.', modelAnswer: 'Nila: What do you like doing after school, Farhan?\nFarhan: I enjoy reading adventure stories. What about you?\nNila: I like gardening with my grandmother.\nFarhan: That sounds peaceful. What do you grow?\nNila: Flowers and a few vegetables. I learn how to care for plants.\nFarhan: I learn new words and ideas from books.\nNila: We should visit the library together one day.\nFarhan: I would like that. Perhaps you can recommend a story.\nNila: Certainly. And you can show me how to find a gardening book.', banglaNote: 'নিজেদের পছন্দ বলার পর একে অন্যকে প্রশ্ন করো; শেষে যৌথ পরিকল্পনা রাখো।' },
    { id: 'c7-email-invitation', grade: 7, type: 'email', title: 'Invite a Friend to Sports Day', unit: 'Unit 7 · Games and Sports', prompt: 'Write an email inviting a friend to your school sports day.', modelAnswer: 'To: Fahim\nSubject: Come to our sports day\n\nDear Fahim,\n\nOur school sports day will be held next Thursday at 9 a.m. on the school field. There will be running races, long jump, relay, and a football match between the classes. I am taking part in the relay race. I would be very happy if you came to watch and cheer for us. Please arrive a little early because the opening ceremony begins at nine. Let me know if you can come.\n\nYour friend,\nSakib', banglaNote: 'তারিখ, সময়, স্থান, কী হবে, এবং বন্ধুকে কেন আমন্ত্রণ জানাচ্ছ—এসব স্পষ্ট করো।' },
    { id: 'c7-letter-study', grade: 7, type: 'letter', title: 'A Letter About My Study Routine', unit: 'Unit 2 · My Study Guide', prompt: 'Write a letter to a friend describing your study routine.', modelAnswer: 'Dear Arif,\n\nI hope you are well. You asked me how I organise my study time. I make a short list of lessons after I return from school. First, I rest and have a snack. Then I finish the most difficult homework while my mind is fresh. I take a small break before reviewing new words and reading a story. I keep my phone away during study time. I do not try to study late at night because sleep is important too. Please tell me how you plan your week.\n\nYour friend,\nHasan', banglaNote: 'সময়ের ক্রম ব্যবহার করো; পড়া, বিরতি, পুনরাবৃত্তি ও ঘুমের ভারসাম্য দেখাও।' },
    { id: 'c7-story-woodcutter', grade: 7, type: 'story', title: 'An Honest Woodcutter', unit: 'Story completion · honesty', prompt: 'Complete a story about a woodcutter who refuses to claim an axe that is not his.', modelAnswer: 'A woodcutter was working beside a river when his axe slipped into the water. He was worried because he had little money. A traveller heard his cry and offered to help. First, the traveller showed him a golden axe. The woodcutter said it belonged to someone else. Then a silver axe appeared, but he refused that one too. At last, the traveller found the woodcutter’s old iron axe. The woodcutter thanked him and explained that it was the only one he owned. The traveller was impressed by his honesty and gave him the golden and silver axes as well.\n\nMoral: Honesty brings its own reward.', banglaNote: 'গল্পের শুরুতে সমস্যা দাও, মাঝখানে তিনটি পরীক্ষা, শেষে সততার ফল দেখাও।' },
    { id: 'c7-story-lion-mouse', grade: 7, type: 'story', title: 'The Lion and the Mouse', unit: 'Story completion · kindness', prompt: 'Complete a story in which a small mouse later helps a lion.', modelAnswer: 'One afternoon, a lion was sleeping in the forest. A little mouse ran across his paw and woke him. The lion caught the mouse, but the mouse asked to be set free and promised to help one day. The lion laughed at the idea, yet he let the mouse go. A few days later, hunters trapped the lion in a net. Hearing his roar, the mouse hurried over and gnawed through the ropes with its sharp teeth. Soon the lion was free. He thanked the small animal and understood that even a little friend can be a great help.\n\nMoral: Kindness is never wasted.', banglaNote: 'ঘটনার ধারাবাহিকতা পরিষ্কার রাখো; ছোট প্রাণীটির কাজেই সমস্যার সমাধান হবে।' },
    { id: 'c7-composition-historic-place', grade: 7, type: 'composition', title: 'A Visit to a Historical Place', unit: 'Travel and heritage', prompt: 'Write a short composition about a visit to a historical place in Bangladesh.', modelAnswer: 'During the winter holiday, my family visited the Shat Gombuj Mosque in Bagerhat. We started early and reached the site before noon. The old mosque has many domes, thick walls, and beautiful arches. A guide told us that it is an important example of the architecture of the Bengal Sultanate. I walked around the site carefully and read the information signs. The place was peaceful, and I imagined how people had gathered there hundreds of years ago. The visit helped me understand why historic buildings should be protected. I returned home with new knowledge and many photographs.', banglaNote: 'স্থানটির নাম, কী দেখেছ, কী শিখেছ, এবং ঐতিহ্য রক্ষার গুরুত্ব উল্লেখ করো।' },

    { id: 'c8-paragraph-food', grade: 8, type: 'paragraph', title: 'Healthy Food Habits', unit: 'Unit 2 · Food and Nutrition', prompt: 'Write a paragraph about healthy food habits for students.', modelAnswer: 'Healthy food habits help students grow, learn, and stay active. A balanced meal includes different kinds of food, such as rice or bread, vegetables, fruit, and a source of protein like fish, eggs, lentils, or beans. Students should drink clean water and eat breakfast before school. Too many sugary snacks may fill us for a short time but do not provide a balanced diet. It is also important to wash hands before eating and keep food covered. No single food makes us healthy by itself. A varied diet, clean water, and regular activity work together to support good health.', banglaNote: 'খাদ্যের ধরন, পরিষ্কার পানি ও পরিচ্ছন্নতা—তিনটি বিষয় যুক্ত করে লেখো।' },
    { id: 'c8-paragraph-hygiene', grade: 8, type: 'paragraph', title: 'Health and Hygiene', unit: 'Unit 3 · Health and Hygiene', prompt: 'Write a paragraph about the importance of health and hygiene.', modelAnswer: 'Good health allows us to study, work, and enjoy time with others. Personal hygiene helps protect us from many common illnesses. We should wash our hands with soap before eating and after using the toilet. Brushing our teeth, wearing clean clothes, and keeping nails short are also useful habits. We need safe drinking water, fresh food, enough sleep, and regular physical exercise. A clean home and school are important because litter can attract insects and block drains. If we feel unwell, we should tell a trusted adult and seek proper medical advice. Healthy habits are simple, but they need regular practice.', banglaNote: 'ব্যক্তিগত পরিচ্ছন্নতা ও পরিবেশ—দুই ধরনের অভ্যাসের উদাহরণ দাও।' },
    { id: 'c8-paragraph-culture', grade: 8, type: 'paragraph', title: 'Folk Culture of Bangladesh', unit: 'Unit 1 · A Glimpse of Our Culture', prompt: 'Write a paragraph about folk culture in Bangladesh.', modelAnswer: 'Bangladesh has a rich folk culture that reflects the lives and creativity of its people. Folk songs tell stories of love, rivers, work, and nature. Nakshi kantha is a traditional embroidered quilt decorated with colourful patterns. Local crafts, children’s songs, and regional foods also show the variety of our culture. Many communities have their own languages, music, clothing, and festivals. We can learn about these traditions by listening to older people, visiting cultural events, and reading reliable books. Respecting different customs helps us understand one another. Folk culture is a living part of our heritage, so it should be remembered and shared.', banglaNote: 'গান, নকশিকাঁথা, খাবার বা স্থানীয় ঐতিহ্য থেকে কয়েকটি উদাহরণ বেছে নাও।' },
    { id: 'c8-paragraph-environment', grade: 8, type: 'paragraph', title: 'Protecting the Environment', unit: 'Unit 5 · Humans and Environment', prompt: 'Write a paragraph about protecting the environment.', modelAnswer: 'The environment includes the air, water, soil, plants, animals, and people around us. It supports life, but careless actions can damage it. Smoke from vehicles and factories makes the air dirty. Plastic waste can block drains and harm animals. We can help by using less plastic, putting rubbish in bins, planting trees, and keeping rivers clean. People should save electricity and water whenever possible. Schools can organise clean-up days and teach students about local wildlife. Protecting the environment is not only the government’s duty; every person can make responsible choices. Small actions become powerful when many people take part.', banglaNote: 'পরিবেশের অংশ, সমস্যা, ব্যক্তিগত কাজ ও সম্মিলিত দায়িত্ব—এই ক্রমে লেখো।' },
    { id: 'c8-paragraph-news', grade: 8, type: 'paragraph', title: 'The Importance of Reliable News', unit: 'Unit 8 · News! News! News!', prompt: 'Write a paragraph about why people need reliable news.', modelAnswer: 'News helps people learn what is happening in their community and in the wider world. Newspapers, radio, television, and trusted online sources report events in different ways. Reliable news gives facts, checks information, and makes clear what is confirmed and what is still uncertain. Readers should compare important reports and think before sharing a message online. False information can frighten people or harm someone’s reputation. Students can practise by checking the source, date, and evidence behind a story. Responsible news use helps us make informed choices and take part in community life.', banglaNote: 'খবরের মাধ্যমের নাম বলো; নির্ভরযোগ্যতা যাচাই ও গুজব না ছড়ানোর কথা যোগ করো।' },
    { id: 'c8-dialogue-trip', grade: 8, type: 'dialogue', title: 'Planning a Class Trip', unit: 'Unit 6 · Going on a Trip', prompt: 'Write a dialogue between two students planning a class trip.', modelAnswer: 'Tania: Our class wants to plan a trip. Where should we go?\nMahir: We could visit a place with nature and a learning centre.\nTania: The teachers mentioned the botanical garden. It is safe and educational.\nMahir: Good choice. We should ask the head teacher for permission first.\nTania: We also need a date, transport, and a list of students.\nMahir: Let us bring reusable water bottles and keep the garden clean.\nTania: I can prepare a permission letter with the class captain.\nMahir: I will ask our teacher about the bus and entry arrangements.\nTania: Great. We can share the plan with everyone tomorrow.', banglaNote: 'স্থান বেছে নেওয়া, অনুমতি, পরিবহন, নিরাপত্তা ও পরিচ্ছন্নতার বিষয় রাখো।' },
    { id: 'c8-dialogue-reading', grade: 8, type: 'dialogue', title: 'The Value of Reading', unit: 'Study and reference skills', prompt: 'Write a dialogue between two friends about the value of reading books.', modelAnswer: 'Rafi: I saw you borrowing a book from the library. What are you reading?\nNusrat: A story about a young explorer. It is exciting and full of new words.\nRafi: I usually read only for class. Does reading help with English?\nNusrat: Yes. It shows how words are used in sentences and gives us ideas.\nRafi: How do you understand a difficult word?\nNusrat: I read the whole sentence first, then check a dictionary if I still need help.\nRafi: That sounds useful. Could you suggest an easy book for me?\nNusrat: Of course. Let us choose one together after class.', banglaNote: 'বই পড়ার আনন্দের পাশাপাশি শব্দভাণ্ডার ও শেখার উপকারটিও দেখাও।' },
    { id: 'c8-dialogue-committee', grade: 8, type: 'dialogue', title: 'Forming a Class Committee', unit: 'Unit 3 · teamwork and school life', prompt: 'Write a dialogue between two students discussing how to form a helpful class committee.', modelAnswer: 'Sadia: Our class needs a committee to organise group activities.\nFahim: We should choose students who listen to everyone, not only their friends.\nSadia: Agreed. We need a chairperson, a note-taker, and volunteers for each task.\nFahim: The committee should also share jobs fairly.\nSadia: How can absent students know what was decided?\nFahim: The note-taker can write a short summary on the class noticeboard.\nSadia: We should ask the teacher to guide us at the first meeting.\nFahim: Good idea. Let us invite the class to suggest names tomorrow.', banglaNote: 'দায়িত্ব ভাগ, সবার মতামত, এবং শিক্ষক/শিক্ষার্থীর সহযোগিতা উল্লেখ করো।' },
    { id: 'c8-email-journey', grade: 8, type: 'email', title: 'Email About a Memorable Journey', unit: 'Unit 6 · Going on a Trip', prompt: 'Write an email to a friend describing a memorable journey.', modelAnswer: 'To: Rashed\nSubject: My journey to Cox’s Bazar\n\nDear Rashed,\n\nLast month my family travelled to Cox’s Bazar by bus. We left before sunrise and watched green fields and small towns pass by. When we arrived, the sea looked wide and blue. I walked along the beach with my parents and collected no shells because we wanted to leave nature undisturbed. In the evening we watched the sunset from a safe place. The journey was long, but the changing scenery made it enjoyable. I hope we can travel together during the next holiday.\n\nBest wishes,\nNadia', banglaNote: 'যাত্রার পথ, গন্তব্যে দেখা দৃশ্য, একটি স্মৃতি ও সমাপ্তির আশা রাখো।' },
    { id: 'c8-story-dove', grade: 8, type: 'story', title: 'The Truthful Dove', unit: 'Unit 10 · Fables', prompt: 'Complete an original fable about a dove that chooses truth over an easy reward.', modelAnswer: 'A dove found a small purse beside a village path. Inside it were a few coins and a card with the owner’s name. A shopkeeper offered the dove a handful of seeds if it kept the purse. The dove refused and carried the purse to the village post office. The postmaster found the owner, an elderly farmer, and returned it. The farmer was grateful because he needed the coins to buy medicine. He offered the dove some seeds as a thank-you, and the dove accepted only after the farmer insisted. The village children learned that telling the truth can help someone in need.\n\nMoral: Do what is right, even when no one is watching.', banglaNote: 'এটি বইয়ের গল্পের হুবহু রূপ নয়—নিজের কাহিনি লেখো; সততার ফল দেখাও।' },
    { id: 'c8-composition-journey', grade: 8, type: 'composition', title: 'A Journey I Remember', unit: 'Unit 6 · Going on a Trip', prompt: 'Write a short composition about a journey you remember.', modelAnswer: 'I will always remember a train journey I took with my family last winter. We reached the station early and checked the platform number on the noticeboard. The train arrived with a loud whistle, and we found our seats beside a window. As it moved away from the city, I saw fields, ponds, bridges, and small stations. My younger brother counted the trees while our parents shared snacks. A station assistant helped an older passenger with a heavy bag. The journey taught me to be patient, follow travel instructions, and respect other passengers. When we reached our destination, I felt tired but happy. It was a simple trip that gave us time together.', banglaNote: 'যাত্রার শুরু, পথে দেখা, একটি ঘটনা, এবং কী শিখেছ—এই চার অংশে সাজাও।' },
    { id: 'c8-composition-culture', grade: 8, type: 'composition', title: 'Our Cultural Heritage', unit: 'Unit 1 · A Glimpse of Our Culture', prompt: 'Write a short composition about the value of Bangladesh’s cultural heritage.', modelAnswer: 'Cultural heritage includes the songs, crafts, stories, food, and traditions that people share across generations. Bangladesh has many examples, such as folk music, nakshi kantha, traditional boat songs, and local festivals. Different communities contribute their own customs and artistic skills. These traditions help us remember where we come from and understand the lives of earlier generations. Heritage is not only something kept in a museum; people keep it alive when they sing, make crafts, tell stories, or celebrate together. We should respect all communities and teach young people about these traditions. In this way, our cultural heritage can continue to grow while remaining connected to the past.', banglaNote: 'ঐতিহ্যের উদাহরণ দাও; অতীতের সঙ্গে বর্তমানের সম্পর্ক ও সংরক্ষণের উপায় বলো।' },

    { id: 'c910-paragraph-trees', grade: 9, type: 'paragraph', title: 'Tree Plantation', unit: 'SSC 2nd Paper · paragraph', prompt: 'Write a paragraph on “Tree Plantation” in about 150–180 words.', modelAnswer: 'Tree plantation means planting young trees in suitable places and caring for them as they grow. Trees absorb carbon dioxide, release oxygen, provide shade, and help keep soil in place. They also give us fruit, timber, medicine, and shelter for birds and animals. Bangladesh needs trees around homes, schools, roads, and open land, but planting should be planned so that native species have room to grow. A sapling must be watered and protected from damage; planting alone is not enough. Students can take part in school campaigns and encourage families to care for trees. Local authorities should protect public green spaces and replace trees that are removed. If communities work together, tree plantation can make neighbourhoods healthier and more resilient.', banglaNote: 'সংজ্ঞা, উপকার, কোথায় লাগাব, কীভাবে যত্ন নেব, এবং শিক্ষার্থী/সরকারের ভূমিকা—এই কাঠামো অনুসরণ করো।' },
    { id: 'c910-paragraph-road', grade: 9, type: 'paragraph', title: 'A Road Accident', unit: 'SSC 2nd Paper · paragraph practice', prompt: 'Write a paragraph about a road accident and ways to reduce such accidents.', modelAnswer: 'A road accident is an unexpected collision or injury involving vehicles, cyclists, or pedestrians. It can happen when a driver speeds, ignores traffic signals, uses a phone, or drives while tired. Poor road conditions and careless crossing can also increase danger. An accident may cause injuries, loss of life, and hardship for families. Everyone has a role in road safety. Drivers should obey speed limits, maintain vehicles, and give way to pedestrians. Passengers should use seat belts where available, while pedestrians should use footbridges or marked crossings. Authorities need clear signs, safe crossings, and regular enforcement of traffic laws. Care and patience on the road can prevent many tragedies.', banglaNote: 'কারণ ও প্রতিরোধ আলাদা করে লেখো; দোষারোপ নয়, নিরাপদ আচরণে জোর দাও।' },
    { id: 'c910-paragraph-loadshedding', grade: 9, type: 'paragraph', title: 'Load Shedding', unit: 'SSC 2nd Paper · paragraph practice', prompt: 'Write a paragraph about load shedding, its effects, and sensible ways to cope.', modelAnswer: 'Load shedding is a temporary interruption of electricity supply when demand is greater than the available supply or when the network needs protection. It can interrupt study, work, transport, and services at home or in a hospital. In hot weather, students may find it difficult to read, and shops may lose working hours. People should use electricity carefully by switching off unused lights and choosing efficient appliances. Families can keep a torch ready and plan essential tasks, but they should never use unsafe indoor generators or candles without care. Long-term solutions include better energy management, reliable infrastructure, and greater use of renewable sources. Responsible use helps, although stable electricity also requires careful planning and investment.', banglaNote: 'সমস্যার অর্থ, প্রভাব, ব্যক্তিগত সতর্কতা ও দীর্ঘমেয়াদি সমাধান—সবই সংক্ষেপে দাও।' },
    { id: 'c910-dialogue-mobile', grade: 9, type: 'dialogue', title: 'Using Mobile Phones Wisely', unit: 'SSC 1st Paper · dialogue practice', prompt: 'Write a dialogue between two friends about using mobile phones wisely.', modelAnswer: 'Rafi: You were checking your phone during lunch. Are you waiting for a message?\nMitu: I was reading a class notice, but I also spent too long scrolling.\nRafi: Phones are useful, but too much screen time can affect sleep and study.\nMitu: True. I can turn off unnecessary notifications while doing homework.\nRafi: We should also check information before sharing it.\nMitu: Yes, and never post someone’s photo without permission.\nRafi: I use a timer so I remember to take breaks.\nMitu: That is a good idea. We can keep phones away during meals too.\nRafi: Let us use technology for learning, but make time for real conversations.\nMitu: Agreed. A phone should be a tool, not the centre of the whole day.', banglaNote: 'সুবিধা ও ঝুঁকি—দুটিই বলো; ব্যবহার সীমা, গোপনীয়তা ও যাচাইয়ের সমাধান দাও।' },
    { id: 'c910-dialogue-dengue', grade: 9, type: 'dialogue', title: 'Preventing Dengue', unit: 'Health and community awareness', prompt: 'Write a dialogue between two classmates about preventing dengue.', modelAnswer: 'Sadia: Our class is preparing a health notice about dengue. What should we include?\nFahim: We should tell people to remove standing water from pots and containers.\nSadia: Some people think one small container does not matter.\nFahim: Mosquitoes can breed in a small amount of still water, so every home should check regularly.\nSadia: Should we use a net or repellent as well?\nFahim: Those can help protect us, especially during the day, but removing breeding places is important too.\nSadia: We should ask an adult for help if we see a large drain or puddle.\nFahim: Right. We must not handle chemicals without guidance.\nSadia: Let us make the notice clear and share it with every class.\nFahim: Good. Prevention works best when the whole community takes part.', banglaNote: 'জমে থাকা পানি সরানো, ব্যক্তিগত সুরক্ষা ও বড় সমস্যায় বড়দের সহায়তা—এই পয়েন্ট রাখো।' },
    { id: 'c910-dialogue-computer', grade: 9, type: 'dialogue', title: 'Learning Computer Skills', unit: 'Unit 15 · Media and Modes of E-communication', prompt: 'Write a dialogue between two friends about the importance of learning computer skills.', modelAnswer: 'Nabil: Our teacher says computer skills are useful for many careers. Which skill should we learn first?\nRupa: We should start with typing, file management, and safe use of the internet.\nNabil: Is it enough to know how to use social media?\nRupa: No. We also need to search carefully, create documents, and recognise false information.\nNabil: I would like to learn how to make a simple presentation.\nRupa: We can practise using the school computer lab and ask our teacher for guidance.\nNabil: We should protect passwords and avoid sharing private details.\nRupa: Exactly. Digital skills are useful when we use them responsibly.\nNabil: Let us make a small study group this week.\nRupa: Good plan. We can learn one skill at a time.', banglaNote: 'দক্ষতার উদাহরণ, শেখার উপায় ও অনলাইন নিরাপত্তা—তিনটিই যুক্ত করো।' },
    { id: 'c910-story-storm', grade: 9, type: 'story', title: 'The Light Beside the Canal', unit: 'SSC 1st Paper · completing story', prompt: 'A storm caused a power cut in a village. On the way home, Rafi saw a small light moving near the canal. Continue the story and give it a suitable title.', modelAnswer: 'Rafi stopped and called out, but nobody answered. The rain was heavy, so he moved carefully along the safe path. Soon he heard a child crying. A little boy had slipped on the muddy bank and was holding a low branch. Rafi put down his schoolbag and called two adults from a nearby house. They brought a rope and a lantern. Together they helped the boy climb to the path. The child was frightened but not badly hurt. Rafi took him to the community clinic, where a nurse checked him. The boy’s parents arrived soon afterward and thanked everyone. Rafi returned home late, tired but relieved. The next day, villagers placed a warning sign near the slippery bank.\n\nTitle: A Light in the Storm', banglaNote: 'শুরুতে রহস্য রাখো, কিন্তু উদ্ধারকে নিরাপদ করো—বড়দের সাহায্য নাও, বিপজ্জনক নায়কোচিত কাজ নয়।' },
    { id: 'c910-story-unity', grade: 9, type: 'story', title: 'The Broken Bridge', unit: 'SSC 1st Paper · completing story', prompt: 'After a storm, a group of neighbours found that the footpath to the village clinic was blocked by fallen branches. Complete the story.', modelAnswer: 'At first, everyone tried to move the largest branches alone, but they were too heavy. The clinic was only a short walk away, and an elderly neighbour needed medicine. The village teacher suggested making a safe team. Some adults cleared small branches, while others marked the muddy area so nobody would slip. Two young people called the local council for help with the larger tree. A shopkeeper brought drinking water for the workers. By afternoon, the path was open enough for people to reach the clinic safely. The council later removed the remaining tree and repaired the path. The neighbours realised that careful cooperation had solved a problem no one could manage alone.\n\nTitle: Many Hands Make Light Work', banglaNote: 'সমস্যা, দলভিত্তিক নিরাপদ কাজ, সাহায্য চাওয়া, এবং সহযোগিতার শিক্ষা—এই ধাপগুলো রাখো।' },
    { id: 'c910-story-fire', grade: 10, type: 'story', title: 'A Small Act of Courage', unit: 'SSC 1st Paper · completing story practice', prompt: 'A student saw smoke coming from a small shop near the school. Complete the story, showing how people respond safely.', modelAnswer: 'The student did not run into the shop. He called the shopkeeper from a safe distance and asked a nearby adult to call the fire service. Another person moved people away from the doorway. The shopkeeper switched off the electricity from the main switch only after an electrician confirmed it was safe. A security guard brought an extinguisher and followed its instructions. The fire service arrived quickly and put out the flames before they spread to the next building. Everyone waited outside until the firefighters said it was safe to return. Later, the student’s teacher praised him for staying calm and asking trained adults for help. The shopkeeper checked the wiring and repaired it before reopening.\n\nTitle: Staying Calm in an Emergency', banglaNote: 'আগুনে ঢুকে পড়া নয়—মানুষকে দূরে সরানো, জরুরি সেবা ডাকা এবং প্রশিক্ষিত সহায়তার ওপর জোর দাও।' },
    { id: 'c910-email-prize', grade: 10, type: 'email', title: 'Email About a Prize-Giving Ceremony', unit: 'SSC 2nd Paper · email practice', prompt: 'Write an email to a friend describing your school’s annual prize-giving ceremony.', modelAnswer: 'To: Farhan\nSubject: Our annual prize-giving ceremony\n\nDear Farhan,\n\nOur school held its annual prize-giving ceremony yesterday. The hall was decorated with flowers and student artwork. After the national anthem, the Head Teacher welcomed the guests and spoke about the year’s achievements. Students received prizes for academic results, sports, debate, and community service. I was happy to receive a certificate for the school magazine. A group performed a short song, and the programme ended with thanks to the teachers and families who helped. I enjoyed the ceremony because it celebrated many kinds of effort, not only exam marks. I wish you could have joined us.\n\nBest wishes,\nMahir', banglaNote: 'ঘটনার সময়, সাজসজ্জা, মূল কার্যক্রম, নিজের অভিজ্ঞতা ও শেষের শুভেচ্ছা—সব রাখো।' },
    { id: 'c910-email-library', grade: 9, type: 'email', title: 'Email Requesting Better Library Facilities', unit: 'SSC 2nd Paper · email/letter practice', prompt: 'Write a polite email to your Head Teacher requesting better facilities in the school library.', modelAnswer: 'To: headteacher@school.edu.bd\nSubject: Request for improved library facilities\n\nDear Sir,\n\nI am writing on behalf of the students of Class Nine to request a few improvements to our school library. The library is useful, but some reference books are old and there are not enough seats for students during the lunch break. We would be grateful if the school could add recent dictionaries and age-appropriate science books, repair the reading tables, and set up a simple borrowing record. Students are willing to help keep the room tidy and return books on time. These changes would make it easier for us to read and study independently. Thank you for considering our request.\n\nYours faithfully,\nA student of Class Nine', banglaNote: 'ইমেইলটি ভদ্র ও বাস্তবসম্মত রাখো; সমস্যার সঙ্গে নির্দিষ্ট সমাধান প্রস্তাব করো।' },
    { id: 'c910-application-debate', grade: 10, type: 'application', title: 'Application for a Debating Club', unit: 'SSC 2nd Paper · application practice', prompt: 'Write an application to your Head Teacher requesting permission to start a debating club.', modelAnswer: '12 October 2026\n\nThe Head Teacher\nMymensingh Model High School\nMymensingh\n\nSubject: Prayer for permission to start a debating club\n\nSir,\n\nWe, the students of your school, respectfully state that many learners are interested in debating, but there is no club where we can practise. Debating would help us organise ideas, speak clearly, listen to different opinions, and build confidence. We therefore request your kind permission to form a debating club under the guidance of an English teacher. We will meet once a week after classes and follow the school’s rules. We would be grateful if you allowed us to use a classroom and noticeboard for our activities.\n\nYours obediently,\nStudents of Class Ten', banglaNote: 'ঠিকানা/তারিখ, subject, কারণ, উপকার, নির্দিষ্ট অনুরোধ ও formal closing—এই বিন্যাস রাখো।' },
    { id: 'c910-composition-science', grade: 9, type: 'composition', title: 'The Wonders of Modern Science', unit: 'SSC 2nd Paper · short composition', prompt: 'Write a short composition on “The Wonders of Modern Science”.', modelAnswer: 'Modern science has changed the way people learn, communicate, travel, and receive medical care. Electricity lights homes and powers many useful machines. Mobile phones let families speak across long distances, while the internet gives students access to lessons, libraries, and news. In hospitals, medical tests and equipment help trained professionals diagnose and treat illness. Improved transport allows people and goods to travel more quickly. Science also supports agriculture through better tools, weather information, and irrigation systems. These benefits bring responsibilities. People should protect private information, check online facts, use energy sensibly, and make sure technology serves human needs. Science is not a substitute for wisdom or kindness. When used carefully and fairly, it can improve daily life and help communities solve difficult problems.', banglaNote: 'আবিষ্কারগুলোর উদাহরণ দাও; প্রতিটি উদাহরণে উপকার দেখিয়ে দায়িত্বশীল ব্যবহারে শেষ করো।' },
    { id: 'c910-composition-aim', grade: 10, type: 'composition', title: 'My Aim in Life', unit: 'SSC 2nd Paper · short composition', prompt: 'Write a short composition on “My Aim in Life”.', modelAnswer: 'Every person needs a goal to guide effort and choices. My aim in life is to become a doctor who serves people in rural communities. Many families live far from a well-equipped hospital, so early advice and dependable medical care can make a great difference. To reach my goal, I must study science carefully, practise English, and develop patience and responsibility. A doctor needs knowledge, but also the ability to listen respectfully to patients. I know the path will require years of hard work, and I may face difficulties along the way. I plan to work steadily and ask my teachers for guidance. If I achieve my aim, I hope to use my skills with honesty and compassion. A worthwhile goal should benefit both the person who pursues it and the community.', banglaNote: 'লক্ষ্য, কেন বেছে নিয়েছ, প্রস্তুতি, সম্ভাব্য বাধা ও সমাজের উপকার—এই ধারায় লেখো।' },
    { id: 'c910-composition-renewable', grade: 10, type: 'composition', title: 'Renewable Energy for Bangladesh', unit: 'Unit 14 · Renewable Energy', prompt: 'Write a short composition on the importance of renewable energy.', modelAnswer: 'Renewable energy comes from sources that are naturally replenished, such as sunlight, wind, and flowing water. It can reduce dependence on fuels that release pollution when burned. Bangladesh receives strong sunlight for much of the year, so solar panels can provide electricity to homes, schools, and clinics, especially in places far from the main grid. Renewable systems may also support irrigation and small businesses. They need careful planning, trained workers, and proper maintenance; no single source can meet every need. Families can save energy by using efficient lights and switching off unused devices. The government, communities, and businesses can work together to expand reliable clean power. Renewable energy is an important part of a healthier and more secure future.', banglaNote: 'নবায়নযোগ্য উৎসের অর্থ, বাংলাদেশের জন্য প্রাসঙ্গিকতা, সুবিধা ও পরিকল্পনার প্রয়োজন উল্লেখ করো।' },
    { id: 'c910-story-woodcutter', grade: 10, type: 'story', title: 'The Honest Traveller', unit: 'SSC 1st Paper · completing story practice', prompt: 'A traveller found a wallet on a crowded bus. Complete the story, showing what the traveller decided to do.', modelAnswer: 'The traveller checked the wallet only to find a name and a phone number on an identity card. He did not count the money or take anything. At the next stop, he told the conductor what he had found and asked him to contact the owner. The owner, a schoolteacher, arrived at the station after work. She checked the wallet and confirmed that it belonged to her. She was relieved because it held the money she needed for a family visit. The traveller returned it without asking for a reward. The teacher thanked him and offered to buy him tea, which he accepted. As they spoke, he learned that the wallet had fallen when she hurried to help an elderly passenger. The honest act made both of them feel hopeful about the kindness of strangers.\n\nTitle: A Wallet Returned', banglaNote: 'চরিত্রের সততা কাজের মাধ্যমে দেখাও; অপ্রয়োজনীয় নাটক না বাড়িয়ে বিশ্বাসযোগ্য সমাপ্তি দাও।' },
    { id: 'c910-composition-climate', grade: 9, type: 'composition', title: 'Climate Change and Bangladesh', unit: 'Unit 2 · Climate Change', prompt: 'Write a short composition on climate change and its effects on Bangladesh.', modelAnswer: 'Climate change refers to long-term shifts in temperature and weather patterns. Bangladesh is especially exposed to its effects because many communities live beside rivers or along the coast. Higher temperatures, irregular rainfall, stronger storms, river erosion, and rising sea levels can threaten homes, farms, and drinking-water sources. When families lose land or crops, they may have to move and begin again elsewhere. Preparedness can reduce some risks. Communities need reliable warnings, safe shelters, strong embankments, and plans that protect people who are most vulnerable. Planting trees, conserving energy, and using cleaner power also support wider efforts to limit climate change. No single action is enough, but informed citizens and careful public planning can make the country more resilient.', banglaNote: 'বাংলাদেশের ঝুঁকির উদাহরণ দাও; প্রভাবের পর মানুষের প্রস্তুতি ও দীর্ঘমেয়াদি পদক্ষেপ বলো।' },
    { id: 'c910-application-debate-g9', grade: 9, type: 'application', title: 'Application for a Debating Club', unit: 'SSC 2nd Paper · application practice', prompt: 'Write an application to your Head Teacher requesting permission to start a debating club.', modelAnswer: '12 October 2026\n\nThe Head Teacher\nMymensingh Model High School\nMymensingh\n\nSubject: Prayer for permission to start a debating club\n\nSir,\n\nWe, the students of Class Nine, respectfully state that many learners are interested in debating, but our school has no club where we can practise. Debating would help us organise ideas, speak clearly, listen to different opinions, and build confidence. We therefore request your permission to form a debating club under the guidance of an English teacher. We will meet once a week after classes and follow the school rules. We would be grateful if you allowed us to use a classroom and noticeboard for our activities.\n\nYours obediently,\nStudents of Class Nine', banglaNote: 'তারিখ, প্রাপক, subject, কারণ, উপকার, নির্দিষ্ট অনুরোধ ও formal closing—এই বিন্যাস রাখো।' },
    { id: 'c910-letter-bookfair', grade: 9, type: 'letter', title: 'A Letter About a Book Fair', unit: 'SSC 2nd Paper · letter practice', prompt: 'Write a letter to a friend describing a book fair you visited.', modelAnswer: 'Mymensingh\n12 October 2026\n\nDear Rima,\n\nI hope you are well. Last Friday I visited the annual book fair with my cousin. Stalls from different publishers displayed storybooks, science books, poems, and dictionaries. I enjoyed looking through the new books and listening to a short discussion by a local writer. The fair was busy, but the organisers kept the walkways clear. I bought a collection of short stories and a small notebook. We also met our English teacher there, who advised us to read a little every day. I wish you had been with us. Let us visit the fair together next year.\n\nWith love,\nNila', banglaNote: 'চিঠিতে কোথায়/কখন গিয়েছিলে, কী দেখেছ, কী কিনেছ এবং বন্ধুকে আমন্ত্রণ—এই বিবরণ রাখো।' },
    { id: 'c910-paragraph-reading', grade: 10, type: 'paragraph', title: 'The Importance of Reading', unit: 'SSC 2nd Paper · paragraph practice', prompt: 'Write a paragraph about the importance of reading for students.', modelAnswer: 'Reading helps students learn beyond the limits of a classroom. A book can introduce new ideas, places, people, and ways of solving problems. Regular reading also builds vocabulary, improves spelling, and helps learners understand how sentences are organised. Students may read stories for enjoyment, newspapers for current information, and reference books for schoolwork. They should choose reliable sources and check facts instead of accepting every claim they see online. A library gives learners a quiet place to read and share books. Even fifteen minutes of reading each day can become a useful habit. Parents and teachers can support it by recommending age-appropriate books and discussing what students have read. Reading develops knowledge, imagination, and independent thinking.', banglaNote: 'পড়ার উপকার, বিভিন্ন উপকরণ, নির্ভরযোগ্য তথ্য বাছাই এবং নিয়মিত অভ্যাস—এই ক্রমে লেখো।' },
    { id: 'c910-dialogue-exam', grade: 10, type: 'dialogue', title: 'Preparing for the SSC Examination', unit: 'SSC 1st Paper · dialogue practice', prompt: 'Write a dialogue between two classmates about preparing sensibly for the SSC examination.', modelAnswer: 'Rafi: The SSC examination is getting closer. Have you made a study plan?\nNila: Yes. I divided the subjects across the week and left time for revision.\nRafi: Do you study for many hours without a break?\nNila: No. I take a short break after each focused study period. It helps me concentrate.\nRafi: I find English writing difficult.\nNila: Practise one paragraph or dialogue at a time, then check the structure and grammar.\nRafi: That sounds manageable. Should we study together once a week?\nNila: Certainly. We can explain difficult topics to each other and ask our teacher when we are unsure.\nRafi: I will also keep my phone away during study time.\nNila: Good idea. Let us work steadily and get enough sleep too.', banglaNote: 'পরিকল্পনা, বিরতি, দুর্বল অংশের অনুশীলন, সহপাঠীর সহায়তা ও বিশ্রাম—বাস্তবসম্মত পরামর্শ দাও।' },
    { id: 'c910-letter-study-tour', grade: 10, type: 'letter', title: 'A Letter About a Study Tour', unit: 'SSC 2nd Paper · letter practice', prompt: 'Write a letter to a friend describing an educational study tour.', modelAnswer: 'Mymensingh\n12 October 2026\n\nDear Arif,\n\nI hope you are doing well. Last week our class went on a study tour to the National Museum in Dhaka. Our teachers divided us into small groups and gave each group a topic to explore. I learned about the Language Movement, our independence, and the work of people who shaped the country. The guide explained the exhibits clearly and reminded us not to touch them. We took notes, asked questions, and ate lunch together in the garden. The tour made some of our history lessons easier to understand. I would like our class to make a short presentation about what we learned. I hope you can join the next tour.\n\nWith best wishes,\nTuhin', banglaNote: 'ভ্রমণের স্থান, শেখার বিষয়, একটি স্মরণীয় অভিজ্ঞতা ও শেষে বন্ধুকে শুভেচ্ছা—এইভাবে লেখো।' }

  ]
};
