// Original editorial selection of practical intermediate English vocabulary.
// Not a frequency ranking, CEFR certification, or a licensed dictionary.
const GROUPS = [
  ['Conversation', `respond reply explain clarify mention describe discuss suggest recommend request remind confirm correct interrupt pause continue emphasize acknowledge apologize compliment persuade negotiate announce introduce address express specify elaborate summarize rephrase interpret pronounce translate quote restate object agree disagree encourage assure reassure invite greet thank welcome excuse complain ask answer listen hear speak talk chat whisper mumble shout argue debate insist admit deny promise comment react`],
  ['Everyday actions', `arrange organize prepare gather collect carry deliver return replace repair restore adjust improve simplify compare select choose sort separate combine attach remove install connect disconnect open close lock unlock fold unfold wrap unwrap store borrow lend rent share offer accept refuse avoid notice observe examine inspect search discover locate identify recognize remember forget practice repeat attempt complete finish restart begin proceed stop settle manage handle maintain support protect prevent rescue assist`],
  ['Thinking and decisions', `consider evaluate assess estimate predict expect assume infer conclude decide determine prioritize plan propose review verify question doubt trust believe realize understand grasp learn recall recognize imagine visualize wonder reflect focus concentrate compare contrast distinguish classify calculate measure investigate research solve adapt revise rethink reconsider compromise commit approve reject hesitate hesitate deliberate judge weigh preference option alternative consequence outcome reason evidence argument assumption judgment perspective insight awareness intention purpose goal approach strategy method principle pattern context detail exception requirement condition possibility probability risk benefit drawback tradeoff priority solution obstacle opportunity challenge progress`],
  ['Feelings', `relieved worried anxious nervous confident uncertain hopeful disappointed frustrated annoyed irritated embarrassed grateful proud curious interested fascinated surprised shocked puzzled confused overwhelmed calm peaceful relaxed comfortable uneasy lonely cheerful joyful delighted content satisfied eager motivated tired exhausted drained stressed sensitive sympathetic considerate respectful affectionate patient resilient optimistic pessimistic cautious enthusiastic sincere genuine openhearted humble appreciative nostalgic restless  doubtful insecure reassured encouraged inspired discouraged`],
  ['Relationships', `friend colleague teammate neighbor partner relative sibling parent guardian cousin guest host stranger acquaintance mentor learner supporter volunteer companion roommate customer client visitor resident contact connection relationship friendship teamwork cooperation agreement boundary respect trust loyalty honesty kindness empathy patience support encouragement conflict disagreement misunderstanding apology forgiveness compromise consideration reliability dependence independence companionship community hospitality generosity`],
  ['Home and routines', `household apartment bedroom kitchen bathroom hallway balcony doorway cupboard drawer shelf blanket pillow mattress curtain towel mirror sink tap drain light switch socket charger kettle pan stove oven fridge freezer laundry basket washing detergent broom mop bucket sponge cloth tidy clutter mess stain leak crack shelf storage repair furniture table chair sofa desk lamp rug cushion lock key spare entrance exit corridor courtyard garden plant pot soil seed waste recycling bin groceries delivery package parcel schedule routine habit task chore appointment reminder rest sleep wake breakfast lunch dinner snack shower commute departure arrival`],
  ['Food and cooking', `ingredient recipe portion serving meal dish flavor taste aroma texture seasoning spice salt pepper sugar flour rice pasta bread dough batter soup broth salad sauce dressing yogurt cheese butter oil vinegar fruit vegetable onion garlic ginger tomato potato carrot bean lentil egg fish chicken meat seafood fresh ripe raw cooked baked roasted grilled fried steamed simmered boiled chopped sliced diced mixed stirred poured measured blended served shared leftover expiry nutrition balanced nutritious allergy appetite hungry thirsty delicious savory sweet sour bitter mild spicy crunchy tender juicy stale spoiled affordable filling homemade takeaway`],
  ['Health and wellbeing', `health healthy illness sickness symptom fever cough cold headache ache pain injury wound bruise swelling rash allergy infection recovery treatment therapy medicine medication prescription pharmacist clinic hospital doctor nurse patient appointment checkup examination diagnosis advice exercise movement stretch walk jog cycle breathing sleep rest fatigue stress anxiety focus hydration water hygiene soap mask vaccine prevention safety emergency urgent routine gradual improvement healing comfort support care nutrition energy stamina strength flexibility balance posture heartbeat temperature pressure breath dizziness nausea soreness fatigue relief`],
  ['Shopping and services', `shop store market stall vendor cashier clerk customer receipt refund exchange return warranty guarantee purchase payment invoice order check-out cart basket stock inventory available unavailable supply demand discount offer deal bargain price cost value budget affordable reasonable expensive cheap quality brand size fit measurement fabric material color pattern style sample label package delivery shipping pickup queue counter booking reservation service support complaint issue request confirmation cancellation policy repair replacement charge fee deposit balance change cash card transfer transaction account`],
  ['Travel and directions', `journey trip route destination departure arrival delay cancellation connection transfer station terminal platform stop schedule timetable ticket fare reservation booking passenger driver conductor vehicle bus train ferry flight bicycle taxi traffic crossing junction intersection bridge tunnel street road lane pavement sidewalk path trail map sign signal direction landmark distance nearby distant local regional border passport luggage baggage suitcase backpack carry-on gate entrance exit security inspection accommodation hotel guesthouse hostel room check-in check-out detour shortcut commute navigation guide tourist visitor itinerary forecast weather delay lost found missed early late on-time`],
  ['Work and projects', `workplace colleague employer employee manager supervisor client customer supplier team meeting agenda minutes deadline task assignment project proposal presentation report update feedback revision draft document file folder spreadsheet record data analysis budget estimate schedule milestone deliverable priority responsibility accountability initiative coordination collaboration communication negotiation agreement contract policy procedure approval request follow-up progress obstacle issue solution outcome performance productivity efficiency accuracy reliability consistency quality safety training support review evaluation promotion interview application vacancy position career skill experience leadership delegation workload handover shift remote hybrid onsite`],
  ['Learning and study', `student teacher tutor lesson class course subject topic unit chapter page paragraph sentence word phrase vocabulary grammar spelling pronunciation meaning definition example explanation instruction direction question answer exercise practice revision review recall memory knowledge understanding skill ability reading writing listening speaking discussion lecture presentation assignment homework deadline submission worksheet notebook textbook dictionary source reference citation evidence claim conclusion summary outline draft edit correction feedback grade score result progress curiosity inquiry investigation experiment observation measurement calculation formula diagram chart graph table comparison contrast research study project library laboratory campus classroom group partner exam test quiz assessment`],
  ['Money and budgeting', `income wage salary allowance savings saving expense spending payment purchase price cost fee charge tax discount bargain refund credit debit debt loan interest rent mortgage deposit balance account transfer cash change bill invoice receipt budget estimate limit value worth profit loss revenue investment insurance subscription instalment installment transaction withdrawal deposit statement currency exchange rate emergency fund financial plan affordable reasonable expensive economical frugal generous wasteful overdue due reserve repay earn borrow lend donate contribute share split cover settle negotiate`],
  ['Technology and communication', `device phone tablet laptop computer screen display keyboard mouse speaker microphone camera battery charger cable adapter wireless network internet connection signal data storage memory file folder document download upload install update upgrade restart reset setting option menu button link browser website webpage app application account profile username password passcode privacy security permission access notification message email inbox attachment reply forward search filter sort save edit delete backup restore sync offline online error bug fix support video call meeting voice recording transcript subtitle translation language font contrast zoom accessibility login logout verification confirmation`],
  ['Nature and weather', `weather forecast climate temperature humidity breeze wind storm thunder lightning rain rainfall drizzle shower flood drought heat sunshine sunlight shadow shade cloud fog mist snow frost ice river lake pond stream waterfall ocean sea coast beach island mountain hill valley forest woodland tree branch leaf root seed flower grass field soil sand mud stone rock wildlife animal bird insect habitat environment pollution recycling conservation protection renewable energy power solar sunlight windmill resource water air carbon emission sustainability erosion season spring summer autumn winter morning evening sunset sunrise`],
  ['Community and civic life', `neighborhood resident citizen community volunteer organizer committee council clinic library school park garden public private local regional service facility event festival celebration meeting announcement notice campaign awareness donation charity support shelter assistance access accessibility inclusion diversity respect cooperation participation contribution leadership improvement planning safety crossing traffic waste collection recycling water supply maintenance repair proposal feedback complaint concern petition policy rule regulation permission registration application deadline opening hours schedule transport healthcare education housing`],
  ['Time and planning', `today tomorrow yesterday morning afternoon evening night weekday weekend calendar date day week month year moment period duration interval appointment schedule timetable deadline reminder routine habit plan priority urgent immediate soon later earlier before after during meanwhile eventually recently previously currently regularly occasionally frequently rarely daily weekly monthly annually temporary permanent flexible available unavailable punctual early late delayed overdue upcoming pending complete finished progress pause continue resume postpone reschedule cancel confirm estimate allow prepare anticipate coordinate arrange organize reserve book`],
  ['Descriptions and qualities', `clear vague precise accurate reliable consistent practical efficient effective useful helpful relevant significant essential necessary optional suitable appropriate reasonable affordable comfortable convenient accessible available secure safe durable sturdy fragile delicate flexible adaptable simple complex complicated detailed concise brief thorough careful cautious confident calm polite respectful honest sincere genuine generous modest humble patient curious eager experienced skilled capable prepared organized tidy messy crowded bustling quiet peaceful noisy gentle harsh warm cool fresh stale ripe tender solid smooth rough bright dim narrow wide spacious compact heavy light strong weak`],
  ['Writing and media', `message note letter email report summary outline draft paragraph chapter headline title caption label comment review article essay story dialogue conversation speech presentation interview announcement notice poster advertisement brochure guide manual instruction description explanation example argument evidence claim source reference quotation citation edit revision correction proofread publish share forward attach download upload record transcript subtitle translation meaning tone voice audience purpose clarity precision structure format grammar punctuation spelling phrase sentence transition connector introduction conclusion`],
  ['Useful expressions', ``]
];
// Expressions are inserted separately as whole units; whitespace separates single-word entries.
const BASE = GROUPS.filter(([topic]) => topic !== 'Useful expressions').flatMap(([topic, text]) => text.split(/\s+/).map(word => ({ word: word.toLowerCase(), topic })));
const EXPRESSIONS = `follow up|meet a deadline|raise a concern|reach an agreement|take responsibility|keep someone updated|set priorities|make a decision|address an issue|request clarification|provide feedback|make an adjustment|manage expectations|reach out|take into account|work out a solution|stick to the plan|share the workload|ask for input|run into a problem|look into it|come up with an idea|put together a proposal|carry out a task|hand over a project|pay attention|take notes|hand in an assignment|catch up|figure out|check your work|draw a conclusion|make a point|back up a claim|look up a word|break down a problem|compare and contrast|take part in a discussion|ask a follow-up question|put an idea into words|see the bigger picture|make a connection|test an assumption|stay on topic|sum up|take a detour|allow extra time|keep in touch|make the most of|keep an open mind|hear someone out|settle in|look out for|follow through|make a difference|give back|speak up|set a boundary|make room|make progress|take a break`.split('|').map(word => ({ word, topic: 'Useful expressions' }));
const seen = new Set();
export const ESSENTIAL_WORDS = [...BASE, ...EXPRESSIONS].filter(entry => {
  if (!/^[a-z][a-z -]{1,55}$/.test(entry.word) || seen.has(entry.word)) return false;
  seen.add(entry.word);
  return true;
});
export const ESSENTIAL_TOPICS = [...new Set(ESSENTIAL_WORDS.map(entry => entry.topic))];
